version: 2.1

references:
  restore-dependencies-cache: &restore-dependencies-cache
    restore_cache:
      keys:
        - deps-1-py<< parameters.version >>-{{ checksum "script/requirements.txt" }}
  install-dependencies: &install-dependencies
    run:
      name: Install Dependencies
      command: |
        python3 -m venv venv
        venv/bin/pip install -r script/requirements.txt
  save-dependencies-cache: &save-dependencies-cache
    save_cache:
      key: deps-1-py<< parameters.version >>-{{ checksum "script/requirements.txt" }}
      paths:
        - venv
  parametrised-python-executor: &parametrised-python-executor
    parameters:
      version:
        type: string
    executor:
      name: python
      version: << parameters.version >>
  python-target-version-only-matrix: &python-target-version-only-matrix
    matrix:
      parameters:
        # Expected runtime is on Python 3.9
        version: ["3.9"]
  python-top-and-bottom-version-matrix: &python-top-and-bottom-version-matrix
    matrix:
      parameters:
        version: ["3.6", "3.9"]


executors:
  python:
    parameters:
      version:
        type: string
    docker:
      - image: circleci/python:<< parameters.version >>

jobs:
  lint:
    <<: *parametrised-python-executor

    steps:
      - checkout

      - *restore-dependencies-cache
      - *install-dependencies
      - *save-dependencies-cache

      - run:
          name: Run Flake8
          command: |
            source venv/bin/activate
            ./script/linting/lint

  typecheck:
    <<: *parametrised-python-executor

    steps:
      - checkout

      - *restore-dependencies-cache
      - *install-dependencies
      - *save-dependencies-cache

      - run:
          name: Run Flake8
          command: |
            source venv/bin/activate
            ./script/typing/check

  check-requirements:
    <<: *parametrised-python-executor

    steps:
      - checkout

      - *restore-dependencies-cache
      - *install-dependencies
      - *save-dependencies-cache

      - run:
          name: Validate runtime requirements file
          command: |
            source venv/bin/activate
            pip-compile && git diff --exit-code

      - run:
          name: Validate development requirements file
          command: |
            source venv/bin/activate
            pip-compile script/requirements.in && git diff --exit-code


workflows:
  version: 2.1

  validate:
    jobs:
      - lint:
          <<: *python-top-and-bottom-version-matrix
      - typecheck:
          <<: *python-top-and-bottom-version-matrix
      - check-requirements:
          <<: *python-target-version-only-matrix
